### ISSUE TITLE
invalid banner check

### ISSUE THREAD

**Issue by olivier-matz-6wind** [leapsecurity/libssh-scanner#13]
Hi,

I'm scanning a version of libssh which is known as vulnerable and I get the following output:

[*] 127.0.0.1:22 is not vulnerable to authentication bypass (SSH-2.0-libssh_0.7.5)

Strangely, the banner does not match because of the _ instead of -.
From what I see in libssh code (libssh/include/libssh/priv.h), the banner is "SSH-2.0-libssh_" SSH_STRINGIFY(LIBSSH_VERSION), so I suppose the scanner should be updated to match an underscore instead of the dash.

After doing the modification, the scanner properly detects the server as "likely VULNERABLE".

By the way, in aggressive mode, the server is seen as not vulnerable, can it be because of the server configuration?

**Comment by jobroche** [comment]
Should be fixed in the latest version, `libssh-scanner 1.0.3`. Try again and let me know.

**Comment by olivier-matz-6wind** [comment]
Hi,

The banner with underscores is properly detected now, thanks.

**Comment by jobroche** [comment]
Awesome thanks!
