### ISSUE TITLE
Crash on some banners

### ISSUE THREAD

**Issue by technion** [leapsecurity/libssh-scanner#14]
Hi,

Thanks a tonne for this tool.  I have found some devices that crash it however. The banner I'm seeing is:

    SSH-1.5-OpenSSH_2.9p1

And when scanned I get
```
Traceback (most recent call last):
  File "./libsshscan.py", line 93, in <module>
    aggressive(ip, int(args.port))
  File "./libsshscan.py", line 57, in aggressive
    pstatus(ip, port, banner)
```

**Comment by jobroche** [comment]
Please try again with the latest version, `libssh-scanner 1.0.3`. Try again and let me know.

**Comment by technion** [comment]
Thanks for looking at this. Unfortunately I'm seeing this:

```
libssh scanner 1.0.3

Searching for Vulnerable Hosts...

Traceback (most recent call last):
  File "./libsshscan.py", line 94, in <module>
    aggressive(ip, int(args.port))
  File "./libsshscan.py", line 57, in aggressive
    pstatus(ip, port, banner)
UnboundLocalError: local variable 'banner' referenced before assignment
```
Appears to be HPE Networking equipment presenting this.

**Comment by jobroche** [comment]
Are you supposed to be getting the same `SSH-1.5-OpenSSH_2.9p1` banner as before? Also, what mode are you running it in?

**Comment by technion** [comment]
I've only previously tried aggressive mode.

I've just tried in standard mode, and it appears to work fine:

```
[*] 172.31.0.79:22 is not vulnerable to authentication bypass (SSH-1.5-OpenSSH_2.9p1)
```

According to the above, that header is still consistent.

**Comment by jobroche** [comment]
Ok! Download the latest version `libssh-scanner 1.0.4` and try again. I'm hoping it should work now.

**Comment by technion** [comment]
Awesome! Can confirm this is resolved.
