### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dareth-koh** [leapsecurity/libssh-scanner#5]
Hi, 
i tried and received syntax error 

C:\Users\me-laptop\AppData\Local\Programs\Python\Python37-32>python scan_libssh.py
  File "scan_libssh.py", line 14
    print "{blue}[*]{white} {ipaddr}:{port} is not vulnerable to authentication bypass ({banner})".format(blue=colors.blue, white=colors.normal, ipaddr=ip, port=port, banner=banner.strip())
                                                                                                 ^
SyntaxError: invalid syntax

Please advise

**Comment by Duck3y** [comment]
Try running in python 2.7. I believe 3+ requires brackets around print statements

**Comment by jobroche** [comment]
Thanks for chiming in @Crathh
