### ISSUE TITLE
version of pyhton required

### ISSUE THREAD

**Issue by azfayel** [leapsecurity/libssh-scanner#8]
The tool installed correctly with the depencies through pip command.
when i run it i have this error msg
<pre># python libsshscan.py
  File &quot;libsshscan.py&quot;, line 14
    print &quot;{blue}[*]{white} {ipaddr}:{port} is not vulnerable to authentication bypass ({banner})&quot;.format(blue=colors.blue, white=colors.normal, ipaddr=ip, port=port, banner=banner.strip()) 
                                                                                                 ^
SyntaxError: invalid syntax
</pre>

So How to overcome ?
Thks in advance

**Comment by Demonslay335** [comment]
Based on the syntax, it seems to be geared towards Python 2.7.
Duplicate of #5.

**Comment by jobroche** [comment]
The latest commits should fix any conflicts due to print statements. Try again @azfayel and thank you @Demonslay335 for chiming in!
